name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and Deploy
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: website
    - name: Run Container
      uses: docker://nginx
      with:
        ports:
          - '8080:80'
        volumes:
          - .:/usr/share/nginx/html:ro
